"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { trpc } from "../../utils/trpc";
import { FORM_TEMPLATES, BUILTIN_THEMES } from "@sec-form/shared";
import { FileText, Eye, BarChart2, Plus, Sparkles, Trash2, ArrowRight, X, AlertCircle } from "lucide-react";
import { LoadingSpinner } from "@sec-form/ui";

export default function DashboardPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const templateParam = searchParams.get("createTemplate");

  const utils = trpc.useUtils();
  
  // Queries
  const { data: formsList, isLoading: isFormsLoading } = trpc.forms.list.useQuery();
  const { data: stats, isLoading: isStatsLoading } = trpc.analytics.getDashboardStats.useQuery();

  // Mutations
  const createFormMutation = trpc.forms.create.useMutation();
  const updateFormMutation = trpc.forms.update.useMutation();
  const deleteFormMutation = trpc.forms.delete.useMutation();
  const generateAIFormMutation = trpc.ai.generateForm.useMutation();

  // Local UI state
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [formTitle, setFormTitle] = useState("");
  const [formDesc, setFormDesc] = useState("");
  
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  
  const [isActionLoading, setIsActionLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  // Handle template import from query parameter on load
  useEffect(() => {
    if (templateParam) {
      const template = FORM_TEMPLATES.find((t) => t.id === templateParam);
      if (template) {
        importTemplate(template);
      }
    }
  }, [templateParam]);

  const importTemplate = async (template: typeof FORM_TEMPLATES[0]) => {
    setIsActionLoading(true);
    setErrorMessage("");
    try {
      // 1. Create a blank form
      const newForm = await createFormMutation.mutateAsync({
        title: template.title,
        description: template.description,
      });

      // 2. Load matched theme or Minimal
      const theme = BUILTIN_THEMES.find((theme) => theme.id === template.themeId) || BUILTIN_THEMES[0];

      // 3. Update the form with the template schema and theme
      await updateFormMutation.mutateAsync({
        id: newForm.id,
        schemaJson: { fields: template.fields as any },
        themeJson: theme as any,
        visibility: "public", // Templates default to public visibility
      });

      // Redirect to builder
      router.push(`/dashboard/builder/${newForm.id}`);
    } catch (e: any) {
      setErrorMessage(e.message || "Failed to import template");
      setIsActionLoading(false);
    }
  };

  const handleStandardCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formTitle.trim()) return;
    
    setIsActionLoading(true);
    setErrorMessage("");
    try {
      const form = await createFormMutation.mutateAsync({
        title: formTitle,
        description: formDesc,
      });
      setIsCreateModalOpen(false);
      router.push(`/dashboard/builder/${form.id}`);
    } catch (e: any) {
      setErrorMessage(e.message || "Failed to create form");
      setIsActionLoading(false);
    }
  };

  const handleAICreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!aiPrompt.trim()) return;

    setIsActionLoading(true);
    setErrorMessage("");
    try {
      // 1. Generate schema from Gemini AI router
      const generatedSchema = await generateAIFormMutation.mutateAsync({
        prompt: aiPrompt,
      });

      // 2. Set title based on prompt
      const title = `AI ${aiPrompt.charAt(0).toUpperCase() + aiPrompt.slice(1)}`;

      // 3. Create database entry
      const form = await createFormMutation.mutateAsync({
        title,
        description: `Generated by AI for prompt: "${aiPrompt}"`,
      });

      // 4. Update the schema
      await updateFormMutation.mutateAsync({
        id: form.id,
        schemaJson: generatedSchema as any,
        visibility: "draft", // Start as draft so developer can edit it
      });

      setIsAIModalOpen(false);
      router.push(`/dashboard/builder/${form.id}`);
    } catch (e: any) {
      setErrorMessage(e.message || "AI generator failed. Try a simpler prompt.");
      setIsActionLoading(false);
    }
  };

  const handleDeleteForm = async (id: string) => {
    if (!confirm("Are you sure you want to delete this form? All submissions will be lost.")) return;
    
    try {
      await deleteFormMutation.mutateAsync({ id });
      utils.forms.list.invalidate();
      utils.analytics.getDashboardStats.invalidate();
    } catch (e: any) {
      alert(e.message || "Failed to delete form");
    }
  };

  const getVisibilityColor = (vis: string) => {
    switch (vis) {
      case "public": return "bg-emerald-50 text-emerald-700 ring-emerald-600/10";
      case "unlisted": return "bg-amber-50 text-amber-700 ring-amber-600/10";
      default: return "bg-slate-100 text-slate-700 ring-slate-600/10";
    }
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      {/* Welcome Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="font-outfit text-3xl font-extrabold text-slate-900">Dashboard</h1>
          <p className="text-slate-500 text-sm mt-1">Create new surveys or analyze response collection dashboards.</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => {
              setAiPrompt("");
              setErrorMessage("");
              setIsAIModalOpen(true);
            }}
            className="inline-flex h-10 items-center gap-1.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-4 text-sm font-semibold text-white shadow-md shadow-indigo-100 hover:opacity-95 transition-all transform hover:-translate-y-0.5"
          >
            <Sparkles className="h-4 w-4" /> Build with AI
          </button>
          <button
            onClick={() => {
              setFormTitle("");
              setFormDesc("");
              setErrorMessage("");
              setIsCreateModalOpen(true);
            }}
            className="inline-flex h-10 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50 shadow-sm transition-colors"
          >
            <Plus className="h-4 w-4" /> Create Form
          </button>
        </div>
      </div>

      {/* STATS OVERVIEW CARDS */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {isStatsLoading ? (
          Array.from({ length: 4 }).map((_, i) => (
            <div key={i} className="h-24 rounded-2xl border border-slate-200 bg-white p-6 animate-pulse" />
          ))
        ) : (
          <>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Total Forms</span>
              <div className="mt-2 text-2xl font-bold font-outfit text-slate-800">{stats?.totalForms || 0}</div>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Form Views</span>
              <div className="mt-2 text-2xl font-bold font-outfit text-slate-800">{stats?.totalViews || 0}</div>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Submissions</span>
              <div className="mt-2 text-2xl font-bold font-outfit text-slate-800">{stats?.totalSubmissions || 0}</div>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Conversion Rate</span>
              <div className="mt-2 text-2xl font-bold font-outfit text-slate-800">{stats?.averageConversionRate || 0}%</div>
            </div>
          </>
        )}
      </div>

      {/* FORMS LIST SECTION */}
      <div>
        <h2 className="font-outfit text-xl font-bold text-slate-900 mb-4">My Forms</h2>

        {isFormsLoading ? (
          <div className="flex items-center justify-center py-20">
            <LoadingSpinner className="w-8 h-8" color="text-indigo-600" />
          </div>
        ) : !formsList || formsList.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center max-w-xl mx-auto">
            <FileText className="h-10 w-10 text-slate-400 mx-auto" />
            <h3 className="mt-4 font-outfit font-bold text-slate-900">No forms built yet</h3>
            <p className="mt-1 text-sm text-slate-500 px-4">Create your first form using our visual builder or let Gemini construct questions using a prompt.</p>
            <button
              onClick={() => setIsAIModalOpen(true)}
              className="mt-6 inline-flex h-9 items-center gap-1.5 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500"
            >
              <Sparkles className="h-4 w-4" /> Start with AI
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {formsList.map((form) => (
              <div
                key={form.id}
                className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between relative group"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className={`inline-flex items-center rounded-md px-2 py-0.5 text-xs font-semibold ring-1 ring-inset ${getVisibilityColor(form.visibility)}`}>
                      {form.visibility}
                    </span>
                    <button
                      onClick={() => handleDeleteForm(form.id)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 opacity-0 group-hover:opacity-100 transition-opacity"
                      title="Delete Form"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>

                  <h3 className="mt-4 font-outfit text-lg font-bold text-slate-950 truncate">{form.title}</h3>
                  <p className="mt-1.5 text-slate-500 text-sm line-clamp-2 min-h-[40px]">{form.description || "No description provided."}</p>
                </div>

                <div className="mt-6 pt-4 border-t border-slate-50 flex items-center justify-between gap-2">
                  <Link
                    href={`/dashboard/builder/${form.id}`}
                    className="inline-flex items-center gap-1.5 text-xs font-bold text-indigo-600 hover:text-indigo-500"
                  >
                    Edit Form <ArrowRight className="h-3.5 w-3.5" />
                  </Link>

                  <div className="flex gap-2">
                    <Link
                      href={`/f/${form.slug}`}
                      target="_blank"
                      className="p-2 rounded-lg border border-slate-200 hover:bg-slate-50 text-slate-500 hover:text-slate-700"
                      title="View Public Form"
                    >
                      <Eye className="h-4 w-4" />
                    </Link>
                    <Link
                      href={`/dashboard/builder/${form.id}?tab=analytics`}
                      className="p-2 rounded-lg border border-slate-200 hover:bg-slate-50 text-slate-500 hover:text-slate-700"
                      title="View Analytics"
                    >
                      <BarChart2 className="h-4 w-4" />
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* MODAL: STANDARD CREATE FORM */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xl max-w-md w-full relative">
            <button
              onClick={() => setIsCreateModalOpen(false)}
              className="absolute right-4 top-4 p-1 rounded-lg text-slate-400 hover:bg-slate-50 hover:text-slate-600"
            >
              <X className="h-5 w-5" />
            </button>

            <h3 className="font-outfit text-xl font-bold text-slate-950 mb-1">Create New Form</h3>
            <p className="text-slate-400 text-xs mb-6">Enter details below to establish a blank form layout.</p>

            {errorMessage && (
              <div className="rounded-lg bg-rose-50 border border-rose-100 text-rose-700 text-xs p-3 mb-4 flex items-center gap-2">
                <AlertCircle className="h-4 w-4 text-rose-600 shrink-0" />
                <span>{errorMessage}</span>
              </div>
            )}

            <form onSubmit={handleStandardCreate} className="space-y-4">
              <div>
                <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-1">Form Title</label>
                <input
                  type="text"
                  value={formTitle}
                  onChange={(e) => setFormTitle(e.target.value)}
                  className="w-full h-10 px-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-600/20 text-sm"
                  placeholder="e.g. Feedback Survey"
                  required
                  disabled={isActionLoading}
                />
              </div>

              <div>
                <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-1">Description (optional)</label>
                <textarea
                  value={formDesc}
                  onChange={(e) => setFormDesc(e.target.value)}
                  className="w-full min-h-[80px] p-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-600/20 text-sm"
                  placeholder="Provide context for respondents..."
                  disabled={isActionLoading}
                />
              </div>

              <div className="flex gap-3 justify-end pt-2">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="h-10 px-4 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold text-sm"
                  disabled={isActionLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="h-10 px-5 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-sm rounded-xl transition-all shadow-sm flex items-center justify-center disabled:opacity-50"
                  disabled={isActionLoading}
                >
                  {isActionLoading ? <LoadingSpinner className="w-4 h-4" color="text-white" /> : "Create Form"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* MODAL: AI FORM BUILDER GENERATOR */}
      {isAIModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xl max-w-md w-full relative">
            <button
              onClick={() => setIsAIModalOpen(false)}
              className="absolute right-4 top-4 p-1 rounded-lg text-slate-400 hover:bg-slate-50 hover:text-slate-600"
            >
              <X className="h-5 w-5" />
            </button>

            <div className="flex items-center gap-1.5 mb-1 text-indigo-700">
              <Sparkles className="h-5 w-5 fill-indigo-100" />
              <h3 className="font-outfit text-xl font-bold text-slate-950">AI Form Generator</h3>
            </div>
            <p className="text-slate-400 text-xs mb-6">Describe the purpose of your form. AI will draft appropriate input fields.</p>

            {errorMessage && (
              <div className="rounded-lg bg-rose-50 border border-rose-100 text-rose-700 text-xs p-3 mb-4 flex items-center gap-2">
                <AlertCircle className="h-4 w-4 text-rose-600 shrink-0" />
                <span>{errorMessage}</span>
              </div>
            )}

            <form onSubmit={handleAICreate} className="space-y-4">
              <div>
                <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-1">Prompt Details</label>
                <textarea
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  className="w-full min-h-[100px] p-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-600/20 text-sm"
                  placeholder="e.g. Create a customer satisfaction feedback form for an e-commerce startup that includes a rating and product categories dropdown"
                  required
                  disabled={isActionLoading}
                />
              </div>

              <div className="flex gap-3 justify-end pt-2">
                <button
                  type="button"
                  onClick={() => setIsAIModalOpen(false)}
                  className="h-10 px-4 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold text-sm"
                  disabled={isActionLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="h-10 px-5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:opacity-95 text-white font-semibold text-sm rounded-xl transition-all shadow-md shadow-indigo-100 flex items-center justify-center gap-1.5 disabled:opacity-50"
                  disabled={isActionLoading}
                >
                  {isActionLoading ? (
                    <>
                      <LoadingSpinner className="w-4 h-4" color="text-white" />
                      <span>Generating schema...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Generate with AI</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
