"use client";

import React, { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { trpc } from "../../utils/trpc";
import { FORM_TEMPLATES, BUILTIN_THEMES } from "@sec-form/shared";
import { Sparkles, Plus } from "lucide-react";
import { FormDrawer } from "../../components/FormDrawer";
import { toast } from "sonner";

import { StatsCardGrid } from "@/components/dashboard/StatsCardGrid";
import { FormCardGrid } from "@/components/dashboard/FormCardGrid";
import { CreateFormModal } from "@/components/dashboard/CreateFormModal";
import { AIFormModal } from "@/components/dashboard/AIFormModal";
import { DashboardHeader } from "@/components/dashboard/DashboardHeader";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useGlobalShortcut } from "@/components/providers/GlobalShortcutProvider";
import { Button } from "@/components/ui/button";
import { useTranslations } from "next-intl";

export default function DashboardPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const templateParam = searchParams.get("createTemplate");
  const t = useTranslations("Dashboard");

  const utils = trpc.useUtils();
  
  // Queries
  const { data: formsList, isLoading: isFormsLoading } = trpc.forms.list.useQuery();
  const { data: stats, isLoading: isStatsLoading } = trpc.analytics.getDashboardStats.useQuery();

  // Mutations
  const createFormMutation = trpc.forms.create.useMutation();
  const updateFormMutation = trpc.forms.update.useMutation();
  const deleteFormMutation = trpc.forms.delete.useMutation();
  const generateAIFormMutation = trpc.ai.generateForm.useMutation();

  // Local UI state
  const [selectedFormForDrawer, setSelectedFormForDrawer] = useState<any | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);

  // Keyboard Shortcuts
  useGlobalShortcut("new-form", "n", "Create New Form", () => {
    setIsCreateModalOpen(true);
  }, "Global Actions");
  
  useGlobalShortcut("ai-form", "g", "Generate AI Form", () => {
    setIsAIModalOpen(true);
  }, "Global Actions");

  // Handle template import from query parameter on load
  useEffect(() => {
    if (templateParam) {
      const template = FORM_TEMPLATES.find((t) => t.id === templateParam);
      if (template) {
        importTemplate(template);
      }
    }
  }, [templateParam]);

  const importTemplate = async (template: typeof FORM_TEMPLATES[0]) => {
    try {
      const newForm = await createFormMutation.mutateAsync({
        title: template.title,
        description: template.description,
      });

      const theme = BUILTIN_THEMES.find((theme) => theme.id === template.themeId) || BUILTIN_THEMES[0];

      await updateFormMutation.mutateAsync({
        id: newForm.id,
        schemaJson: { fields: template.fields as any },
        themeJson: theme as any,
        visibility: "public",
      });

      router.push(`/dashboard/builder/${newForm.id}`);
    } catch (e: any) {
      toast.error(e.message || "Failed to import template");
    }
  };

  const handleCreateForm = async (title: string, description: string) => {
    const form = await createFormMutation.mutateAsync({
      title,
      description,
    });
    router.push(`/dashboard/builder/${form.id}`);
  };

  const handleAICreateForm = async (prompt: string) => {
    const generatedSchema = await generateAIFormMutation.mutateAsync({
      prompt,
    });

    const title = `AI ${prompt.charAt(0).toUpperCase() + prompt.slice(1)}`;

    const form = await createFormMutation.mutateAsync({
      title,
      description: `Generated by AI for prompt: "${prompt}"`,
    });

    await updateFormMutation.mutateAsync({
      id: form.id,
      schemaJson: generatedSchema as any,
      visibility: "draft",
    });

    router.push(`/dashboard/builder/${form.id}`);
  };

  const handleDeleteForm = async (id: string) => {
    try {
      await deleteFormMutation.mutateAsync({ id });
      utils.forms.list.invalidate();
      utils.analytics.getDashboardStats.invalidate();
      if (selectedFormForDrawer?.id === id) {
        setSelectedFormForDrawer(null);
      }
      toast.success("Form deleted successfully");
    } catch (e: any) {
      toast.error(e.message || "Failed to delete form");
    }
  };

  return (
    <div className="flex h-full w-full overflow-hidden bg-transparent">
      {/* Main dashboard content (Left side) */}
      <div className="flex-1 flex flex-col h-full overflow-hidden min-w-0">
        {/* Page Header (Pinned & Harmonized) */}
        <DashboardHeader title={t("navDashboard")}>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                onClick={() => setIsAIModalOpen(true)}
                className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-4 text-xs font-semibold text-white shadow-sm hover:opacity-95 transition-all"
              >
                <Sparkles className="h-4 w-4" /> {t("generateAi")}
              </Button>
            </TooltipTrigger>
            <TooltipContent>Generate AI Form [G]</TooltipContent>
          </Tooltip>

          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                onClick={() => setIsCreateModalOpen(true)}
                variant="outline"
                className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-border bg-card px-4 text-xs font-semibold text-muted-foreground hover:bg-accent hover:text-accent-foreground shadow-sm transition-colors"
              >
                <Plus className="h-4 w-4" /> {t("newForm")}
              </Button>
            </TooltipTrigger>
            <TooltipContent>Create New Form [N]</TooltipContent>
          </Tooltip>
        </DashboardHeader>

        {/* Scrollable Body area */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 sm:p-8">
          <div className="max-w-6xl mx-auto space-y-8">
            {/* STATS OVERVIEW CARDS */}
            <StatsCardGrid stats={stats} isStatsLoading={isStatsLoading} />

            {/* FORMS LIST SECTION */}
            <div>
              <h2 className="font-outfit text-xl font-bold text-foreground mb-4">{t("title")}</h2>

              <FormCardGrid
                formsList={formsList}
                isFormsLoading={isFormsLoading}
                setSelectedFormForDrawer={setSelectedFormForDrawer}
                handleDeleteForm={handleDeleteForm}
                setIsAIModalOpen={setIsAIModalOpen}
                isSidebarOpen={!!selectedFormForDrawer}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Right Sidebar panel (sliding in Next.js content side-by-side) */}
      <div
        className={`border-l border-border h-full bg-card/95 backdrop-blur-md flex flex-col transition-all duration-300 shadow-xl shrink-0 z-30 ${
          selectedFormForDrawer ? "w-full sm:w-[450px]" : "w-0 overflow-hidden border-l-0"
        }`}
      >
        {selectedFormForDrawer && (
          <FormDrawer
            form={selectedFormForDrawer}
            onClose={() => setSelectedFormForDrawer(null)}
            isSidebarMode={true}
          />
        )}
      </div>

      {/* MODAL: STANDARD CREATE FORM */}
      <CreateFormModal
        isOpen={isCreateModalOpen}
        setIsOpen={setIsCreateModalOpen}
        onCreate={handleCreateForm}
      />

      {/* MODAL: AI FORM BUILDER GENERATOR */}
      <AIFormModal
        isOpen={isAIModalOpen}
        setIsOpen={setIsAIModalOpen}
        onGenerate={handleAICreateForm}
      />
    </div>
  );
}
