"use client";

import React, { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { motion } from "motion/react";
import { FORM_TEMPLATES, BUILTIN_THEMES } from "@sec-form/shared";
import { Sparkles, Plus, Search, Filter, Layers, Globe, FileEdit, LinkIcon } from "lucide-react";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

import { FormCardGrid } from "@/components/dashboard/FormCardGrid";
import { CreateFormModal } from "@/components/dashboard/CreateFormModal";
import { AIFormModal } from "@/components/dashboard/AIFormModal";
import { DashboardHeader } from "@/components/dashboard/DashboardHeader";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useGlobalShortcut } from "@/components/providers/GlobalShortcutProvider";
import { TabBar } from "@/components/TabBar";
import { Button } from "@/components/ui/button";
import { useTranslations } from "next-intl";
import { useSession } from "next-auth/react";
import { FormDrawer } from "@/components/FormDrawer";
import trpc from "@/utils/trpc";
import { getLocalForms, saveLocalForm, deleteLocalForm, addDeletedSeededFormId, getDeletedSeededFormIds, LocalForm } from "@/utils/localForms";

export default function DashboardPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const templateParam = searchParams.get("createTemplate");
  const t = useTranslations("Dashboard");

  const utils = trpc.useUtils();
  
  const { data: session } = useSession();
  const isDemo = session?.user?.email === "demo@demo.com";

  // Queries
  const { data: formsList, isLoading: isFormsLoading } = trpc.forms.list.useQuery();
  const { data: stats, isLoading: isStatsLoading } = trpc.analytics.getDashboardStats.useQuery();

  const [localUpdateTrigger, setLocalUpdateTrigger] = useState(0);

  const combinedForms = React.useMemo(() => {
    if (!formsList) return [];
    if (!isDemo) return formsList;
    
    const localForms = getLocalForms();
    const deletedSeededIds = getDeletedSeededFormIds();
    const localFormIds = new Set(localForms.map(f => f.id));
    const deletedSeededIdsSet = new Set(deletedSeededIds);

    const dbFormsFiltered = formsList.filter(f => !localFormIds.has(f.id) && !deletedSeededIdsSet.has(f.id));

    return [...localForms, ...dbFormsFiltered].sort((a, b) => 
      new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
    );
  }, [formsList, isDemo, localUpdateTrigger]);

  const aiFormsCount = combinedForms?.filter((f: any) => f.description?.includes("Generated by AI")).length || 0;
  const aiCredits = Math.max(0, 2 - aiFormsCount);

  // Mutations
  const createFormMutation = trpc.forms.create.useMutation();
  const updateFormMutation = trpc.forms.update.useMutation();
  const deleteFormMutation = trpc.forms.delete.useMutation();
  const generateAIFormMutation = trpc.ai.generateForm.useMutation();

  // Local UI state
  const [selectedFormForDrawer, setSelectedFormForDrawer] = useState<any | null>(null);
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  
  // Filters state
  const [searchQuery, setSearchQuery] = useState("");
  const [visibilityFilter, setVisibilityFilter] = useState<"all" | "public" | "unlisted">("all");

  const filteredForms = combinedForms?.filter((form) => {
    const matchesSearch = form.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          (form.description?.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesVisibility = visibilityFilter === "all" || form.visibility === visibilityFilter;
    return matchesSearch && matchesVisibility;
  });

  useGlobalShortcut("new-form", "n", "Create New Form", () => {
    setIsCreateModalOpen(true);
  }, "Global Actions");
  
  useGlobalShortcut("ai-form", "g", "Generate AI Form", () => {
    setIsAIModalOpen(true);
  }, "Global Actions");

  useGlobalShortcut("filter-all", "shift+1", "Filter: All", () => {
    setVisibilityFilter("all");
  }, "Filters");

  useGlobalShortcut("filter-public", "shift+2", "Filter: Public", () => {
    setVisibilityFilter("public");
  }, "Filters");

  useGlobalShortcut("filter-unlisted", "shift+3", "Filter: Unlisted", () => {
    setVisibilityFilter("unlisted");
  }, "Filters");

  // Handle template import from query parameter on load
  useEffect(() => {
    if (templateParam) {
      const template = FORM_TEMPLATES.find((t) => t.id === templateParam);
      if (template) {
        importTemplate(template);
      }
    }
  }, [templateParam]);

  const importTemplate = async (template: typeof FORM_TEMPLATES[0]) => {
    try {
      const theme = BUILTIN_THEMES.find((theme) => theme.id === template.themeId) || BUILTIN_THEMES[0];
      if (isDemo) {
        const id = crypto.randomUUID();
        const localForm: LocalForm = {
          id,
          title: template.title,
          description: template.description,
          slug: `form-${Math.random().toString(36).substring(2, 8)}`,
          visibility: "draft",
          schemaJson: { fields: template.fields as any },
          themeJson: theme as any,
          userId: "demo-user-id",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        saveLocalForm(localForm);
        setLocalUpdateTrigger(prev => prev + 1);
        router.push(`/dashboard/my-forms/${id}/edit`);
        return;
      }

      const newForm = await createFormMutation.mutateAsync({
        title: template.title,
        description: template.description,
      });

      await updateFormMutation.mutateAsync({
        id: newForm.id,
        schemaJson: { fields: template.fields as any },
        themeJson: theme as any,
        visibility: "draft",
      });

      router.push(`/dashboard/my-forms/${newForm.id}/edit`);
    } catch (e: any) {
      toast.error(e.message || "Failed to import template");
    }
  };

  const handleCreateForm = async (title: string, description: string) => {
    if (isDemo) {
      const id = crypto.randomUUID();
      const localForm: LocalForm = {
        id,
        title,
        description,
        slug: `form-${Math.random().toString(36).substring(2, 8)}`,
        visibility: "draft",
        schemaJson: {
          fields: [
            {
              id: crypto.randomUUID(),
              type: "text" as const,
              label: "Untitled Question",
              required: false,
              placeholder: "",
            },
          ],
        },
        userId: "demo-user-id",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      saveLocalForm(localForm);
      setLocalUpdateTrigger(prev => prev + 1);
      router.push(`/dashboard/my-forms/${id}/edit`);
      return;
    }
    const form = await createFormMutation.mutateAsync({
      title,
      description,
    });
    router.push(`/dashboard/my-forms/${form.id}/edit`);
  };

  const handleAICreateForm = async (prompt: string) => {
    try {
      const generatedSchema = await generateAIFormMutation.mutateAsync({
        prompt,
      });

      const title = `AI ${prompt.charAt(0).toUpperCase() + prompt.slice(1)}`;

      if (isDemo) {
        const id = crypto.randomUUID();
        const localForm: LocalForm = {
          id,
          title,
          description: `Generated by AI for prompt: "${prompt}"`,
          slug: `form-${Math.random().toString(36).substring(2, 8)}`,
          visibility: "draft",
          schemaJson: generatedSchema as any,
          userId: "demo-user-id",
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        saveLocalForm(localForm);
        setLocalUpdateTrigger(prev => prev + 1);
        router.push(`/dashboard/my-forms/${id}/edit`);
        return;
      }

      const form = await createFormMutation.mutateAsync({
        title,
        description: `Generated by AI for prompt: "${prompt}"`,
      });

      await updateFormMutation.mutateAsync({
        id: form.id,
        schemaJson: generatedSchema as any,
        visibility: "draft",
      });

      router.push(`/dashboard/my-forms/${form.id}/edit`);
    } catch (e: any) {
      toast.error(e.message || "Failed to generate AI form");
    }
  };

  const handleDeleteForm = async (id: string) => {
    if (isDemo) {
      try {
        const localForms = getLocalForms();
        const isLocal = localForms.some(f => f.id === id);
        if (isLocal) {
          deleteLocalForm(id);
        } else {
          addDeletedSeededFormId(id);
        }
        setLocalUpdateTrigger(prev => prev + 1);
        if (selectedFormForDrawer?.id === id) {
          setSelectedFormForDrawer(null);
        }
        toast.success("Form deleted successfully");
      } catch (e: any) {
        toast.error(e.message || "Failed to delete form");
      }
      return;
    }
    try {
      await deleteFormMutation.mutateAsync({ id });
      utils.forms.list.invalidate();
      utils.analytics.getDashboardStats.invalidate();
      if (selectedFormForDrawer?.id === id) {
        setSelectedFormForDrawer(null);
      }
      toast.success("Form deleted successfully");
    } catch (e: any) {
      toast.error(e.message || "Failed to delete form");
    }
  };

  return (
    <div className="flex h-full w-full overflow-hidden bg-transparent">
      {/* Main dashboard content (Left side) */}
      <div className="flex-1 flex flex-col h-full overflow-hidden min-w-0">
        {/* Page Header (Pinned & Harmonized) */}
        <DashboardHeader title={t("navMyForms") || "My Forms"}>
          <Tooltip>
            <TooltipTrigger asChild>
              <motion.div
                whileHover={{ scale: 1.03, transition: { type: "tween" as const, ease: "linear" as const, duration: 0.1 } }}
                whileTap={{ scale: 0.97, transition: { type: "tween" as const, ease: "linear" as const, duration: 0.08 } }}
                className="inline-block"
              >
                <Button
                  onClick={() => setIsAIModalOpen(true)}
                  className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-gradient-to-r from-primary to-pink-500 px-4 text-xs font-semibold text-white shadow-sm hover:opacity-95 transition-all"
                >
                  <Sparkles className="h-4 w-4" /> {isDemo ? t("generateAi") : `${t("generateAi")} (${aiCredits}/2)`}
                </Button>
              </motion.div>
            </TooltipTrigger>
            <TooltipContent>Generate AI Form [G]</TooltipContent>
          </Tooltip>

          <Tooltip>
            <TooltipTrigger asChild>
              <motion.div
                whileHover={{ scale: 1.03, transition: { type: "tween" as const, ease: "linear" as const, duration: 0.1 } }}
                whileTap={{ scale: 0.97, transition: { type: "tween" as const, ease: "linear" as const, duration: 0.08 } }}
                className="inline-block"
              >
                <Button
                  onClick={() => setIsCreateModalOpen(true)}
                  variant="outline"
                  className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-border bg-card px-4 text-xs font-semibold text-muted-foreground hover:bg-accent hover:text-accent-foreground shadow-sm transition-colors"
                >
                  <Plus className="h-4 w-4" /> {t("newForm")}
                </Button>
              </motion.div>
            </TooltipTrigger>
            <TooltipContent>Create New Form [N]</TooltipContent>
          </Tooltip>
        </DashboardHeader>

        {/* Scrollable Body area */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 sm:p-8">
          <div className="max-w-6xl mx-auto space-y-8">
            {/* FORMS LIST SECTION */}
            <div className="space-y-6">
              <div className="sticky top-0 z-20 flex flex-col sm:flex-row gap-4 items-center justify-between -mx-4 sm:mx-0 rounded-none sm:rounded-2xl bg-transparent pointer-events-none">
                <div className="relative w-full sm:w-80 backdrop-blur-sm pointer-events-auto">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Search forms..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-9 h-10 w-full bg-background/50 border-border rounded-xl text-sm transition-colors focus:bg-background"
                  />
                </div>
                <div className="relative h-14 w-full sm:w-[450px]">
                  <TabBar
                    items={[
                      { value: "all", label: "All Forms", icon: Layers, shortcut: "Shift+1" },
                      { value: "public", label: "Public", icon: Globe, shortcut: "Shift+2" },
                      { value: "unlisted", label: "Unlisted", icon: LinkIcon, shortcut: "Shift+3" },
                    ]}
                    selectedValue={visibilityFilter}
                    onChange={(val) => setVisibilityFilter(val as any)}
                    fullWidth
                  />
                </div>
              </div>

              <FormCardGrid
                formsList={filteredForms}
                isFormsLoading={isFormsLoading}
                setSelectedFormForDrawer={setSelectedFormForDrawer}
                handleDeleteForm={handleDeleteForm}
                setIsAIModalOpen={setIsAIModalOpen}
                isSidebarOpen={!!selectedFormForDrawer}
                isDemo={isDemo}
                aiCredits={aiCredits}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Right Sidebar panel (sliding in Next.js content side-by-side) */}
      <div
        className={`border-l border-border h-full bg-card/95 backdrop-blur-md flex flex-col transition-all duration-300 shadow-xl shrink-0 z-30 ${
          selectedFormForDrawer ? "w-full sm:w-[450px]" : "w-0 overflow-hidden border-l-0"
        }`}
      >
        {selectedFormForDrawer && (
          <FormDrawer
            form={selectedFormForDrawer}
            onClose={() => setSelectedFormForDrawer(null)}
            isSidebarMode={true}
          />
        )}
      </div>

      {/* MODAL: STANDARD CREATE FORM */}
      <CreateFormModal
        isOpen={isCreateModalOpen}
        setIsOpen={setIsCreateModalOpen}
        onCreate={handleCreateForm}
      />

      {/* MODAL: AI FORM BUILDER GENERATOR */}
      <AIFormModal
        isOpen={isAIModalOpen}
        setIsOpen={setIsAIModalOpen}
        onGenerate={handleAICreateForm}
        isDemo={isDemo}
        aiCredits={aiCredits}
      />
    </div>
  );
}
